[_]
schema-version = "0.2"

[[io.buildpacks.group]]
id = "heroku/nodejs"
version = "*"

[io.buildpacks.build.env]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
YARN_PRODUCTION = "false"
NODE_VERBOSE = "true"
